import type { Language, LocalizedText } from "../journey-data";
import type { ClaimField, PilotStep } from "./pilot-types";

export const pt = (value: LocalizedText, language: Language) => value[language];

export const pilotCopy = {
  pilotName: { en: "David's live-thread pilot", ar: "تجربة ديفيد على خيط عمل حي" },
  assisted: { en: "Founder-assisted", ar: "بمساعدة المؤسِّسة" },
  noIntegrations: { en: "No live integrations", ar: "من دون تكاملات مباشرة" },
  support: { en: "Ask the pilot operator", ar: "اسأل مسؤولة التجربة" },
  savedLocal: { en: "Saved in this browser", ar: "محفوظ في هذا المتصفح" },
  saveFailed: {
    en: "This browser could not preserve the latest change. Export a recovery file before leaving.",
    ar: "تعذّر على هذا المتصفح حفظ أحدث تغيير. صدّر ملف استعادة قبل المغادرة.",
  },
  stepOf: { en: "Step", ar: "الخطوة" },
  of: { en: "of", ar: "من" },
  estimated: { en: "Estimated effort", ar: "الوقت المتوقع" },
  whatNext: { en: "What happens next", ar: "ما الذي سيحدث بعد ذلك" },
  whyStep: { en: "Why this step exists", ar: "لماذا توجد هذه الخطوة" },
  dataBoundary: { en: "Data boundary", ar: "حدود البيانات" },
  deleteData: { en: "Delete this pilot from this browser", ar: "احذف هذه التجربة من هذا المتصفح" },
  exportRecovery: { en: "Export recovery file", ar: "صدّر ملف استعادة" },
  resume: { en: "Resume pilot", ar: "تابع التجربة" },
  continue: { en: "Continue", ar: "متابعة" },
  back: { en: "Back", ar: "رجوع" },
  optional: { en: "Optional", ar: "اختياري" },
  required: { en: "Required", ar: "مطلوب" },
  localOnly: {
    en: "Nothing is uploaded automatically. Thread material stays in this browser until you deliberately download and email the pilot packet. Use a trusted device: Ulomis does not add encryption to browser storage.",
    ar: "لا يُرفع شيء تلقائيًا. تبقى مواد الخيط في هذا المتصفح حتى تنزّل حزمة التجربة وترسلها بالبريد عمدًا. استخدم جهازًا موثوقًا؛ لا يضيف أولوميس تشفيرًا إلى تخزين المتصفح.",
  },
  welcomeEyebrow: { en: "One real workflow. One measurable test.", ar: "سير عمل حقيقي واحد. اختبار واحد قابل للقياس." },
  welcomeTitle: { en: "Use Ulomis on one live client thread", ar: "استخدم أولوميس على خيط عميل حي واحد" },
  welcomeBody: {
    en: "You provide the fragments you would normally reopen. We configure a source-backed operational state. You correct only what would mislead the work. When you return, we measure whether you resumed with less admin and reconstruction.",
    ar: "تقدّم الأجزاء التي تعود إليها عادةً. نهيّئ حالة تشغيلية مدعومة بالمصادر. تصحّح فقط ما قد يضلّل العمل. وعندما تعود، نقيس ما إذا تابعت بجهد إداري وإعادة بناء أقل.",
  },
  yourPart: { en: "Your part", ar: "دورك" },
  yourPartBody: {
    en: "Choose one safe thread, record a short baseline, add the existing material, and later correct only what matters.",
    ar: "اختر خيطًا آمنًا، وسجّل خط أساس مختصرًا، وأضف المواد الموجودة، ثم صحّح لاحقًا ما يهم فقط.",
  },
  ourPart: { en: "Our part", ar: "دورنا" },
  ourPartBody: {
    en: "Organize the evidence, reconstruct the current state, attach provenance, expose uncertainty, and return a continuity file for your review.",
    ar: "ننظّم الأدلة، ونعيد بناء الحالة الحالية، ونرفق مصادرها، ونكشف عدم اليقين، ونعيد ملف استمرارية لمراجعتك.",
  },
  success: { en: "What success means", ar: "ما معنى النجاح" },
  successBody: {
    en: "On re-entry, you reach a confident next action faster, reopen fewer sources, or avoid coordination you would normally need. If that does not happen, the test has not demonstrated value.",
    ar: "عند العودة، تصل إلى خطوة تالية واثقة أسرع، أو تفتح مصادر أقل، أو تتجنب تنسيقًا كنت ستحتاج إليه. إن لم يحدث ذلك، فلم تُثبت التجربة قيمة.",
  },
  begin: { en: "Begin with one client thread", ar: "ابدأ بخيط عميل واحد" },
  welcomeTime: { en: "8–12 minutes now, then one short return visit", ar: "من 8 إلى 12 دقيقة الآن، ثم عودة قصيرة واحدة" },
  welcomeNext: {
    en: "You will first check that the thread can produce a valid re-entry test.",
    ar: "ستتحقق أولًا من أن الخيط يصلح لاختبار عودة حقيقي.",
  },
  qualificationTitle: { en: "Choose a thread that can prove or disprove the claim", ar: "اختر خيطًا يمكنه إثبات الادعاء أو نفيه" },
  qualificationBody: {
    en: "Use one active client thread you expect to reopen in 2–7 days. It should span more than one source and still contain a decision, dependency, follow-up, or unresolved item.",
    ar: "استخدم خيط عميل نشطًا تتوقع العودة إليه خلال يومين إلى سبعة أيام. يجب أن يمتد عبر أكثر من مصدر وأن يتضمن قرارًا أو اعتمادًا أو متابعة أو بندًا غير محسوم.",
  },
  threadLabel: { en: "Private thread label", ar: "عنوان خاص للخيط" },
  threadLabelHelp: { en: "Use an anonymous label; a client name is not required.", ar: "استخدم عنوانًا مجهولًا؛ لا حاجة إلى اسم العميل." },
  expectedReturn: { en: "When do you expect to reopen it?", ar: "متى تتوقع العودة إليه؟" },
  shortContext: { en: "One-sentence context", ar: "سياق في جملة واحدة" },
  active: { en: "The thread is active now", ar: "الخيط نشط الآن" },
  clientFacing: { en: "It affects a live client outcome", ar: "يؤثر في نتيجة عميل حية" },
  multiSource: { en: "I normally reopen at least two sources", ar: "أعود عادةً إلى مصدرين على الأقل" },
  hasOpenLoop: { en: "A decision, dependency, follow-up, or unresolved item remains", ar: "ما زال هناك قرار أو اعتماد أو متابعة أو بند غير محسوم" },
  safeToShare: { en: "I can share a redacted version lawfully and safely", ar: "يمكنني مشاركة نسخة منقحة بصورة قانونية وآمنة" },
  suitable: { en: "Suitable for a re-entry test", ar: "مناسب لاختبار العودة" },
  notSuitable: { en: "Not suitable yet", ar: "غير مناسب بعد" },
  qualificationError: {
    en: "Choose a return date 2–7 days from today and confirm every suitability condition.",
    ar: "اختر تاريخ عودة بعد يومين إلى سبعة أيام وأكّد جميع شروط الملاءمة.",
  },
  lockThread: { en: "Use this thread and record the baseline", ar: "استخدم هذا الخيط وسجّل خط الأساس" },
  qualificationTime: { en: "2 minutes", ar: "دقيقتان" },
  qualificationNext: {
    en: "Before Ulomis sees the material, you will record what re-entry normally costs.",
    ar: "قبل أن يرى أولوميس المواد، ستسجّل تكلفة العودة المعتادة.",
  },
  baselineTitle: { en: "Record the normal reconstruction burden first", ar: "سجّل عبء إعادة البناء المعتاد أولًا" },
  baselineBody: {
    en: "This timestamped baseline prevents us from claiming savings after the fact. Use your best realistic estimate for this exact type of thread.",
    ar: "يمنع خط الأساس المؤرخ ادعاء وفورات بأثر رجعي. استخدم أفضل تقدير واقعي لهذا النوع من الخيوط تحديدًا.",
  },
  normalMinutes: { en: "Minutes normally needed before you can act", ar: "الدقائق اللازمة عادةً قبل أن تتمكن من التصرف" },
  normalAdminMinutes: { en: "Admin minutes normally spent reconstructing or coordinating", ar: "دقائق الإدارة التي تُقضى عادةً في إعادة البناء أو التنسيق" },
  normalSources: { en: "Sources normally reopened", ar: "عدد المصادر التي تفتحها عادةً" },
  normalPeople: { en: "People normally contacted", ar: "عدد الأشخاص الذين تتواصل معهم عادةً" },
  baselineDefinitions: {
    en: "Re-entry time is the full elapsed time until you know what to do next. Admin time is the portion spent searching, rereading, reconstructing, or coordinating; it cannot exceed the total.",
    ar: "زمن العودة هو الوقت الكامل حتى تعرف ما يجب فعله بعد ذلك. أما الوقت الإداري فهو الجزء الذي يُقضى في البحث أو إعادة القراءة أو إعادة البناء أو التنسيق، ولا يمكن أن يتجاوز المجموع.",
  },
  stateConfidence: { en: "Confidence in the current state", ar: "الثقة في الحالة الحالية" },
  actionConfidence: { en: "Confidence in the next action", ar: "الثقة في الخطوة التالية" },
  friction: { en: "What normally makes this thread hard to resume?", ar: "ما الذي يجعل العودة إلى هذا الخيط صعبة عادةً؟" },
  confidenceScale: { en: "1 = unclear · 5 = very clear", ar: "1 = غير واضح · 5 = واضح جدًا" },
  lockBaseline: { en: "Lock baseline and add the material", ar: "ثبّت خط الأساس وأضف المواد" },
  baselineTime: { en: "2 minutes", ar: "دقيقتان" },
  baselineNext: {
    en: "You will add the fragments you would normally reopen, without reorganizing them for Ulomis.",
    ar: "ستضيف الأجزاء التي تعود إليها عادةً من دون إعادة تنظيمها لأجل أولوميس.",
  },
  intakeTitle: { en: "Add the material as it already exists", ar: "أضف المواد كما هي" },
  intakeBody: {
    en: "Paste excerpts, add links, or attach the files you would normally inspect. Do not summarize or classify the workflow for us.",
    ar: "الصق مقتطفات أو أضف روابط أو أرفق الملفات التي تفحصها عادةً. لا تلخّص سير العمل ولا تصنّفه لنا.",
  },
  addText: { en: "Add pasted material", ar: "أضف مادة ملصقة" },
  addFiles: { en: "Add files", ar: "أضف ملفات" },
  addLink: { en: "Add a link reference", ar: "أضف مرجع رابط" },
  sourceType: { en: "Source type", ar: "نوع المصدر" },
  sourceLabel: { en: "Short source label", ar: "عنوان قصير للمصدر" },
  sourceDate: { en: "Source date or relative time", ar: "تاريخ المصدر أو وقته النسبي" },
  sourceText: { en: "Paste the relevant excerpt", ar: "الصق المقتطف ذي الصلة" },
  sourceLink: { en: "Reference URL", ar: "رابط المرجع" },
  sourceStatus: { en: "Handling status", ar: "حالة المعالجة" },
  included: { en: "Included", ar: "مضمّن" },
  redacted: { en: "Redacted", ar: "منقّح" },
  excluded: { en: "Excluded", ar: "مستبعد" },
  clarification: { en: "Needs clarification", ar: "يحتاج توضيحًا" },
  addSource: { en: "Add source", ar: "أضف المصدر" },
  remove: { en: "Remove", ar: "إزالة" },
  attachmentLimit: {
    en: "Accepted: PDF, DOC/DOCX, TXT, Markdown, CSV, JSON, and images. Maximum 5 MB per file and 12 MB total.",
    ar: "المقبول: PDF وDOC/DOCX وTXT وMarkdown وCSV وJSON والصور. الحد الأقصى 5 ميغابايت للملف و12 ميغابايت إجمالًا.",
  },
  permissionConsent: { en: "I am permitted to use this redacted material for this pilot.", ar: "لدي إذن باستخدام هذه المواد المنقحة في التجربة." },
  redactionConsent: { en: "I removed credentials and unnecessary personal, pricing, or confidential details.", ar: "أزلت بيانات الدخول والتفاصيل الشخصية أو السعرية أو السرية غير اللازمة." },
  boundaryConsent: {
    en: "I understand export creates a separate copy and email is not encrypted; I will send only permitted, redacted material or use an agreed secure transfer method.",
    ar: "أفهم أن التصدير ينشئ نسخة منفصلة وأن البريد غير مشفر؛ سأرسل فقط مواد منقحة ومسموحًا بها أو أستخدم وسيلة نقل آمنة متفقًا عليها.",
  },
  sourceMinimum: { en: "Add at least two included or redacted sources.", ar: "أضف مصدرين مضمّنين أو منقحين على الأقل." },
  preparePacket: { en: "Prepare the pilot packet", ar: "حضّر حزمة التجربة" },
  intakeTime: { en: "4–7 minutes", ar: "من 4 إلى 7 دقائق" },
  intakeNext: {
    en: "A single local packet will download. You will attach it to an email so the Ulomis team can prepare the continuity view.",
    ar: "ستنزل حزمة محلية واحدة. سترفقها برسالة بريد ليتمكن فريق أولوميس من إعداد عرض الاستمرارية.",
  },
  processingTitle: { en: "Your material is ready for founder-assisted reconstruction", ar: "موادك جاهزة لإعادة البناء بمساعدة المؤسِّسة" },
  processingBody: {
    en: "The packet is not transmitted automatically. Send the downloaded file to the pilot operator. We will return a prepared continuity file; nothing becomes confirmed until you review it.",
    ar: "لا تُرسل الحزمة تلقائيًا. أرسل الملف المنزل إلى مسؤولة التجربة. سنعيد ملف استمرارية مُعدًا، ولن يصبح شيء مؤكدًا حتى تراجعه.",
  },
  packetPrepared: { en: "1. Pilot packet prepared", ar: "1. تم إعداد حزمة التجربة" },
  sendPacket: { en: "2. Send the packet", ar: "2. أرسل الحزمة" },
  reconstruction: { en: "3. Ulomis prepares the operational state", ar: "3. يُعد أولوميس الحالة التشغيلية" },
  importContinuity: { en: "4. Import the returned continuity file", ar: "4. استورد ملف الاستمرارية المعاد" },
  downloadAgain: { en: "Download packet again", ar: "نزّل الحزمة مجددًا" },
  openEmail: { en: "Open email instructions", ar: "افتح تعليمات البريد" },
  markSent: { en: "I attached and sent the packet", ar: "أرفقت الحزمة وأرسلتها" },
  sent: { en: "Packet marked as sent", ar: "تم تعليم الحزمة كمرسلة" },
  noAction: { en: "Your effort during preparation: none, unless we ask one bounded clarification.", ar: "جهدك أثناء الإعداد: لا شيء، إلا إذا طلبنا توضيحًا محدودًا واحدًا." },
  emailBoundary: {
    en: "Email is not an encrypted client-data channel. Send only material you are permitted to share and have redacted. Use an agreed secure transfer method instead when the workflow requires it.",
    ar: "البريد الإلكتروني ليس قناة مشفرة لبيانات العملاء. أرسل فقط المواد المسموح بمشاركتها بعد تنقيحها. استخدم وسيلة نقل آمنة متفقًا عليها عندما يتطلب سير العمل ذلك.",
  },
  importFile: { en: "Import prepared continuity file", ar: "استورد ملف الاستمرارية المُعد" },
  processingTime: { en: "No active work while the view is prepared", ar: "لا عمل مطلوب أثناء إعداد العرض" },
  processingNext: {
    en: "When the file is ready, you will review the operational state and correct only material errors.",
    ar: "عندما يصبح الملف جاهزًا، ستراجع الحالة التشغيلية وتصحح الأخطاء الجوهرية فقط.",
  },
  returnToIntakeConfirm: {
    en: "Returning to the material step may invalidate the packet already sent. If you change or re-export anything, you must send the new packet before importing a continuity file. Return anyway?",
    ar: "قد تؤدي العودة إلى خطوة المواد إلى إبطال الحزمة المرسلة. إذا غيّرت أو أعدت تصدير أي شيء، فيجب إرسال الحزمة الجديدة قبل استيراد ملف الاستمرارية. هل تريد الرجوع؟",
  },
  intakeRevisionWarning: {
    en: "A packet was already prepared for this pilot. Any source or consent change invalidates that packet and all derived continuity. Prepare and send a new packet before continuing.",
    ar: "سبق إعداد حزمة لهذه التجربة. أي تغيير في المصادر أو الموافقات يُبطل تلك الحزمة وكل حالة استمرارية مشتقة منها. حضّر حزمة جديدة وأرسلها قبل المتابعة.",
  },
  reviewTitle: { en: "Confirm the state you would actually resume from", ar: "أكّد الحالة التي ستعود منها فعليًا" },
  reviewBody: {
    en: "This is a draft reconstruction, not a summary and not yet a fact. Correct only anything that would change the work, the open loop, or the next action.",
    ar: "هذه إعادة بناء أولية، وليست ملخصًا ولا حقيقة مؤكدة بعد. صحّح فقط ما سيغيّر العمل أو البند المفتوح أو الخطوة التالية.",
  },
  draft: { en: "Draft reconstruction — not yet confirmed", ar: "إعادة بناء أولية — غير مؤكدة بعد" },
  whyShown: { en: "Why this appears", ar: "لماذا يظهر هذا" },
  classification: { en: "Type", ar: "النوع" },
  confidence: { en: "Confidence", ar: "الثقة" },
  sources: { en: "Sources", ar: "المصادر" },
  lastConfirmed: { en: "Last confirmed", ar: "آخر تأكيد" },
  correctItem: { en: "Correct this item", ar: "صحّح هذا البند" },
  looksRight: { en: "Looks right", ar: "يبدو صحيحًا" },
  correctedText: { en: "What should the operational state say instead?", ar: "ماذا يجب أن تقول الحالة التشغيلية بدلًا من ذلك؟" },
  correctionReason: { en: "Brief reason", ar: "سبب مختصر" },
  reviseAction: { en: "Only if this changes the next action, replace it here", ar: "فقط إن غيّر هذا الخطوة التالية، استبدلها هنا" },
  applyCorrection: { en: "Apply correction", ar: "طبّق التصحيح" },
  cancel: { en: "Cancel", ar: "إلغاء" },
  effectiveAction: { en: "Next action after corrections", ar: "الخطوة التالية بعد التصحيحات" },
  confirmAccuracy: { en: "This state is accurate enough for me to resume the work without rebuilding it first.", ar: "هذه الحالة دقيقة بما يكفي لأتابع العمل من دون إعادة بنائه أولًا." },
  confirmThread: { en: "Confirm thread and set up re-entry", ar: "أكّد الخيط وجهّز اختبار العودة" },
  reviewTime: { en: "3–5 minutes", ar: "من 3 إلى 5 دقائق" },
  reviewNext: {
    en: "The confirmed state will be preserved. You will leave it, then return when you next need to work on this thread.",
    ar: "ستُحفظ الحالة المؤكدة. ستغادرها ثم تعود عندما تحتاج إلى العمل على هذا الخيط مجددًا.",
  },
  awaitingTitle: { en: "The thread is ready for the re-entry test", ar: "الخيط جاهز لاختبار العودة" },
  awaitingBody: {
    en: "Leave the work here. When you next need this client thread, open this same link first—before reopening the original sources where practical.",
    ar: "اترك العمل هنا. عندما تحتاج إلى خيط العميل مجددًا، افتح الرابط نفسه أولًا قبل إعادة فتح المصادر الأصلية قدر الإمكان.",
  },
  returnTarget: { en: "Expected return", ar: "العودة المتوقعة" },
  preserved: { en: "What Ulomis preserved", ar: "ما الذي حفظه أولوميس" },
  returnInstructions: {
    en: "When you return: start the timer, use the continuity view, open original sources only if needed, and count them. Stop the timer when you know what to do next.",
    ar: "عندما تعود: ابدأ المؤقت، واستخدم عرض الاستمرارية، وافتح المصادر الأصلية عند الحاجة فقط، واحسبها. أوقف المؤقت عندما تعرف ما يجب فعله بعد ذلك.",
  },
  copyLink: { en: "Copy this return link", ar: "انسخ رابط العودة" },
  returningNow: { en: "I am returning to this thread now", ar: "أعود إلى هذا الخيط الآن" },
  notYet: { en: "Not yet — keep it preserved", ar: "ليس الآن — أبقه محفوظًا" },
  reentryTitle: { en: "Resume from the preserved state", ar: "تابع من الحالة المحفوظة" },
  reentryBody: {
    en: "The timer measures the path from opening Ulomis to knowing the next action. Use the view first. Record any source or person you still need.",
    ar: "يقيس المؤقت المسار من فتح أولوميس إلى معرفة الخطوة التالية. استخدم العرض أولًا. سجّل أي مصدر أو شخص ما زلت تحتاج إليه.",
  },
  elapsed: { en: "Re-entry time", ar: "زمن العودة" },
  sourceOpened: { en: "I reopened a source", ar: "فتحت مصدرًا" },
  personContacted: { en: "I contacted a person", ar: "تواصلت مع شخص" },
  readyToAct: { en: "I know what to do next", ar: "أعرف ما يجب فعله بعد ذلك" },
  reentryTime: { en: "Measured live", ar: "مقاس مباشرة" },
  reentryNext: {
    en: "You will compare this observed return with the baseline and decide whether a second thread is warranted.",
    ar: "ستقارن هذه العودة المرصودة بخط الأساس وتقرر ما إذا كان خيط ثانٍ مبررًا.",
  },
  resultTitle: { en: "Record what actually happened", ar: "سجّل ما حدث فعليًا" },
  resultBody: {
    en: "Do not reward the concept. Record the observable result. One thread can show value, but it cannot prove repeatability.",
    ar: "لا تكافئ الفكرة. سجّل النتيجة المرصودة. يمكن لخيط واحد أن يظهر قيمة، لكنه لا يثبت قابلية التكرار.",
  },
  correctionsOnReturn: { en: "Additional corrections needed on return", ar: "تصحيحات إضافية مطلوبة عند العودة" },
  actualAdminMinutes: { en: "Admin minutes actually spent on this return", ar: "دقائق الإدارة التي قُضيت فعليًا في هذه العودة" },
  actualAdminHelp: {
    en: "Count only searching, rereading, reconstruction, and coordination within the measured return. This cannot exceed the live re-entry time.",
    ar: "احسب فقط البحث وإعادة القراءة وإعادة البناء والتنسيق ضمن العودة المقاسة. لا يمكن أن يتجاوز ذلك زمن العودة المباشر.",
  },
  actionTaken: { en: "Did you take the next action?", ar: "هل نفذت الخطوة التالية؟" },
  duplicatedAvoided: { en: "Was duplicated work avoided?", ar: "هل تم تجنب عمل مكرر؟" },
  followupsAvoided: { en: "Were follow-ups avoided?", ar: "هل تم تجنب متابعات؟" },
  coordinationAvoided: { en: "Coordination steps avoided", ar: "خطوات التنسيق التي تم تجنبها" },
  resultNotes: { en: "What materially helped or failed?", ar: "ما الذي ساعد أو فشل بصورة جوهرية؟" },
  yes: { en: "Yes", ar: "نعم" },
  no: { en: "No", ar: "لا" },
  unknown: { en: "Not sure", ar: "غير متأكد" },
  observedResult: { en: "Observed result from this one thread", ar: "النتيجة المرصودة من هذا الخيط الواحد" },
  minutesSaved: { en: "Re-entry minutes saved", ar: "دقائق العودة الموفرة" },
  adminMinutesSaved: { en: "Admin minutes saved", ar: "دقائق الإدارة الموفرة" },
  minutesLonger: { en: "Re-entry minutes longer", ar: "دقائق إضافية في العودة" },
  sourcesAvoided: { en: "Sources not reopened", ar: "مصادر لم تُفتح مجددًا" },
  contactsAvoided: { en: "People not contacted", ar: "أشخاص لم يتم التواصل معهم" },
  noSaving: { en: "No time saving observed", ar: "لم تُرصد وفورات زمنية" },
  decisionTitle: { en: "What should happen next?", ar: "ماذا يجب أن يحدث بعد ذلك؟" },
  secondThread: { en: "Material value — test a second live thread", ar: "قيمة جوهرية — اختبر خيطًا حيًا ثانيًا" },
  reviseRepeat: { en: "Partial value — revise and repeat once", ar: "قيمة جزئية — عدّل وكرر مرة واحدة" },
  stop: { en: "No material value — stop this workflow test", ar: "لا قيمة جوهرية — أوقف اختبار سير العمل" },
  finalize: { en: "Finalize the pilot record", ar: "أغلق سجل التجربة" },
  exportOutcome: { en: "Download outcome report", ar: "نزّل تقرير النتيجة" },
  exportArchive: { en: "Download full pilot archive", ar: "نزّل أرشيف التجربة الكامل" },
  emailOutcome: { en: "Email the outcome", ar: "أرسل النتيجة بالبريد" },
  finalized: { en: "Pilot record finalized", ar: "تم إغلاق سجل التجربة" },
  singleThreadBoundary: {
    en: "This result is one observed workflow. A second real thread is the minimum behavioural test of repeat use; payment or sponsorship is a separate commercial test.",
    ar: "هذه نتيجة سير عمل واحد مرصود. الخيط الحقيقي الثاني هو الحد الأدنى لاختبار تكرار الاستخدام؛ أما الدفع أو الرعاية فاختبار تجاري منفصل.",
  },
  referallPromise: {
    en: "ReferAll work already moves across systems, spreadsheets, and calendars. This pilot tests whether one live client thread can be resumed with less reconstruction and admin—not whether the concept sounds useful.",
    ar: "يتنقل عمل ReferAll بالفعل بين الأنظمة والجداول والتقويمات. تختبر هذه التجربة ما إذا كان يمكن استئناف خيط عميل حي واحد بإعادة بناء وجهد إداري أقل، لا ما إذا كانت الفكرة تبدو مفيدة.",
  },
  notFeedbackSession: {
    en: "You are not being asked to reorganize the thread, design the product, or give general feedback. Use the workflow once and correct only state that would mislead the work.",
    ar: "لا نطلب منك إعادة تنظيم الخيط أو تصميم المنتج أو تقديم ملاحظات عامة. استخدم سير العمل مرة واحدة وصحّح فقط الحالة التي قد تضلّل العمل.",
  },
  exactSequence: { en: "Exactly what will happen", ar: "ما الذي سيحدث بالضبط" },
  sequenceChooseTitle: { en: "Choose one active thread", ar: "اختر خيطًا نشطًا واحدًا" },
  sequenceChooseBody: { en: "A client thread you expect to reopen in 2–7 days.", ar: "خيط عميل تتوقع العودة إليه خلال يومين إلى سبعة أيام." },
  sequenceBaselineTitle: { en: "Record the baseline", ar: "سجّل خط الأساس" },
  sequenceBaselineBody: { en: "Your normal re-entry time, admin, sources, contacts, and confidence.", ar: "زمن العودة المعتاد والجهد الإداري والمصادر والاتصالات والثقة." },
  sequenceMaterialTitle: { en: "Add existing fragments", ar: "أضف الأجزاء الموجودة" },
  sequenceMaterialBody: { en: "No reorganization, integration, or new tracker required.", ar: "لا حاجة إلى إعادة تنظيم أو تكامل أو متتبع جديد." },
  sequenceReviewTitle: { en: "Correct only material state", ar: "صحّح الحالة الجوهرية فقط" },
  sequenceReviewBody: { en: "Nothing becomes confirmed until you review it.", ar: "لا يصبح شيء مؤكدًا حتى تراجعه." },
  sequenceReturnTitle: { en: "Leave and return", ar: "غادر ثم عُد" },
  sequenceReturnBody: { en: "The real test happens after an interruption.", ar: "يحدث الاختبار الحقيقي بعد انقطاع." },
  sequenceResultTitle: { en: "Compare the observed result", ar: "قارن النتيجة المرصودة" },
  sequenceResultBody: { en: "Continue only if the workflow materially helped.", ar: "استمر فقط إذا ساعد سير العمل بصورة جوهرية." },
  pilotContinuity: { en: "Pilot continuity", ar: "استمرارية التجربة" },
  lastChange: { en: "Last change", ar: "آخر تغيير" },
  pilotRecord: { en: "Pilot record", ar: "سجل التجربة" },
  trackedEvents: { en: "tracked events", ar: "أحداث متتبعة" },
  exportAudit: { en: "Export non-content audit log", ar: "صدّر سجل تدقيق بلا محتوى الخيط" },
  importRecovery: { en: "Import recovery file", ar: "استورد ملف استعادة" },
  openingPilot: { en: "Opening the pilot…", ar: "جارٍ فتح التجربة…" },
  actionNeeded: { en: "Action needed", ar: "إجراء مطلوب" },
  workingLocally: { en: "Working locally…", ar: "جارٍ العمل محليًا…" },
  minutes: { en: "minutes", ar: "دقائق" },
  placeholderThread: { en: "Example: Referral onboarding — anonymous client A", ar: "مثال: إعداد إحالة — العميل المجهول أ" },
  placeholderContext: { en: "What is moving, and what is still unresolved? Do not include a client name.", ar: "ما الذي يتحرك، وما الذي لا يزال غير محسوم؟ لا تذكر اسم العميل." },
  placeholderFriction: { en: "Example: I forget why a date moved and reopen email, the CRM, and my calendar before I can respond.", ar: "مثال: أنسى سبب تغيير الموعد فأعيد فتح البريد ونظام العملاء والتقويم قبل أن أتمكن من الرد." },
  sourceDateExample: { en: "Example: 2 days ago or 2026-08-01", ar: "مثال: قبل يومين أو 2026-08-01" },
  materialAdded: { en: "Material added", ar: "المواد المضافة" },
  textUsage: { en: "Text", ar: "النص" },
  filesUsage: { en: "Files", ar: "الملفات" },
  timeNotSupplied: { en: "time not supplied", ar: "لم يُذكر الوقت" },
  noMaterial: { en: "No material added yet. Add the sources you would normally reopen.", ar: "لم تُضف مواد بعد. أضف المصادر التي تفتحها عادةً عند العودة." },
  usableSources: { en: "usable sources", ar: "مصادر صالحة" },
  beforeExport: { en: "Before export", ar: "قبل التصدير" },
  transferDeliberately: { en: "Transfer the packet deliberately", ar: "انقل الحزمة عمدًا" },
  transferDeliberatelyBody: {
    en: "No thread material leaves this browser until you attach the downloaded packet yourself. The pilot operator reconstructs the state manually and returns a separate file.",
    ar: "لا تغادر مواد الخيط هذا المتصفح حتى ترفق الحزمة المنزلة بنفسك. تعيد مسؤولة التجربة بناء الحالة يدويًا وتعيد ملفًا منفصلًا.",
  },
  transferBoundaryLabel: { en: "Transfer boundary", ar: "حدود النقل" },
  continuityReady: { en: "Continuity file ready?", ar: "هل أصبح ملف الاستمرارية جاهزًا؟" },
  continuityReadyBody: {
    en: "Import the file whose name begins with ulomis-continuity-. The app verifies that its pilot ID and evidence references match this thread.",
    ar: "استورد الملف الذي يبدأ اسمه بـ ulomis-continuity-. يتحقق التطبيق من تطابق معرّف التجربة ومراجع الأدلة مع هذا الخيط.",
  },
  attachPacketDetail: {
    en: "Attach the downloaded JSON file to the email. Email links cannot attach files automatically.",
    ar: "أرفق ملف JSON المنزّل بالبريد. لا تستطيع روابط البريد إرفاق الملفات تلقائيًا.",
  },
  packetDownloaded: { en: "Packet downloaded", ar: "تم تنزيل الحزمة" },
  reconstructionPending: {
    en: "Founder-assisted reconstruction from only the material in this packet. Unsupported claims must be marked uncertain or missing.",
    ar: "إعادة بناء بمساعدة المؤسِّسة اعتمادًا فقط على مواد هذه الحزمة. يجب تعليم الادعاءات غير المدعومة بأنها غير مؤكدة أو مفقودة.",
  },
  preparationDeadline: { en: "Target delivery", ar: "موعد التسليم المستهدف" },
  deadlineCommitment: {
    en: "If this target changes, the pilot operator must tell you before the stated time. Until then, no action is required from you.",
    ar: "إذا تغيّر هذا الموعد، يجب على مسؤولة التجربة إبلاغك قبل الوقت المذكور. وحتى ذلك الحين، لا يلزمك أي إجراء.",
  },
  draftUnconfirmedBody: {
    en: "Nothing is treated as confirmed until you approve the operational state.",
    ar: "لا يُعامل شيء على أنه مؤكد حتى تعتمد الحالة التشغيلية.",
  },
  suggestionBoundary: {
    en: "Suggestion only. You remain responsible for the decision and execution.",
    ar: "هذا اقتراح فقط. تظل مسؤولًا عن القرار والتنفيذ.",
  },
  materialCorrections: { en: "Material corrections recorded", ar: "التصحيحات الجوهرية المسجلة" },
  noWorkUntilReturn: { en: "No work until you naturally return", ar: "لا عمل حتى تعود بصورة طبيعية" },
  confirmedAt: { en: "Confirmed", ar: "تم التأكيد" },
  nextActionLabel: { en: "Next action", ar: "الخطوة التالية" },
  returnProtocol: { en: "Return protocol", ar: "بروتوكول العودة" },
  startOnlyOnReturn: {
    en: "Press this only when you are genuinely returning to work on the client thread.",
    ar: "اضغط هذا فقط عندما تعود فعلًا للعمل على خيط العميل.",
  },
  earlyReturnWarning: {
    en: "This is earlier than the return date you selected. Starting now is allowed only if you are genuinely resuming the client work; the outcome will be marked as weaker interruption evidence.",
    ar: "هذا أبكر من تاريخ العودة الذي اخترته. لا تبدأ الآن إلا إذا كنت تستأنف عمل العميل فعلًا؛ وستُعلَّم النتيجة كدليل أضعف على الانقطاع.",
  },
  earlyReturnConfirm: {
    en: "You selected a later return date. Are you genuinely returning to this client work now? Starting early will be recorded and weakens the re-entry evidence.",
    ar: "لقد اخترت تاريخ عودة لاحقًا. هل تعود فعلًا إلى عمل هذا العميل الآن؟ سيُسجَّل البدء المبكر ويجعل دليل العودة أضعف.",
  },
  interruptionObserved: {
    en: "Interruption observed",
    ar: "الانقطاع المرصود",
  },
  earlyEvidenceBoundary: {
    en: "The return began before the selected date, so this result must not be described as a normal 2–7 day re-entry test.",
    ar: "بدأت العودة قبل التاريخ المختار، لذلك لا يجوز وصف هذه النتيجة بأنها اختبار عودة اعتيادي بعد يومين إلى سبعة أيام.",
  },
  timerBoundary: {
    en: "The operational state remains hidden until the timer starts. The timer survives refresh and stops when you state that you know the next action.",
    ar: "تبقى الحالة التشغيلية مخفية حتى يبدأ المؤقت. يستمر المؤقت بعد تحديث الصفحة ويتوقف عندما تقر بأنك تعرف الخطوة التالية.",
  },
  sameDeviceBoundary: {
    en: "Return on this same browser and device. The page address does not contain your thread state. To move devices or recover after storage loss, use the recovery file.",
    ar: "عُد من المتصفح والجهاز نفسيهما. لا يحتوي عنوان الصفحة على حالة الخيط. للانتقال إلى جهاز آخر أو الاستعادة بعد فقد التخزين، استخدم ملف الاستعادة.",
  },
  whereLeft: { en: "Where you left it", ar: "هنا توقفت" },
  resultTime: { en: "3 minutes", ar: "3 دقائق" },
  resultNext: {
    en: "The pilot ends with an explicit second-thread, revise-and-repeat, or stop decision.",
    ar: "تنتهي التجربة بقرار صريح: خيط ثانٍ، أو تعديل وتكرار، أو توقف.",
  },
  selfReportedBaseline: { en: "self-reported baseline", ar: "خط أساس مُبلّغ ذاتيًا" },
  observed: { en: "observed", ar: "مرصود" },
  reopened: { en: "reopened", ar: "أُعيد فتحها" },
  contacted: { en: "contacted", ar: "تم التواصل معهم" },
  resultCalculationBoundary: {
    en: "The result is calculated from David’s timestamped, self-reported baseline and the live re-entry timer. Negative values remain visible; they are never converted into savings.",
    ar: "تُحسب النتيجة من خط أساس ديفيد المؤرخ والمبلّغ ذاتيًا ومن مؤقت العودة المباشر. تبقى القيم السلبية ظاهرة ولا تُحوّل أبدًا إلى وفورات.",
  },
  adminMinutesLonger: { en: "Additional admin minutes", ar: "دقائق إدارية إضافية" },
  noAdminSaving: { en: "No admin-time saving observed", ar: "لم تُرصد وفورات في الوقت الإداري" },
  additionalSources: { en: "Additional sources reopened", ar: "مصادر إضافية أُعيد فتحها" },
  noSourceReduction: { en: "No source reduction observed", ar: "لم يُرصد انخفاض في المصادر" },
  additionalContacts: { en: "Additional people contacted", ar: "أشخاص إضافيون تم التواصل معهم" },
  noContactReduction: { en: "No contact reduction observed", ar: "لم يُرصد انخفاض في الاتصالات" },
  afterReentry: { en: "after re-entry", ar: "بعد العودة" },
  finalizedDetail: {
    en: "Export and send the non-content outcome report. Retain the full archive only when needed and permitted.",
    ar: "صدّر وأرسل تقرير النتيجة الخالي من محتوى الخيط. احتفظ بالأرشيف الكامل فقط عند الحاجة والسماح.",
  },
  sourceFallback: {
    en: "No direct source was attached. Treat this item as unverified and requiring confirmation.",
    ar: "لم يُرفق مصدر مباشر. تعامل مع هذا البند على أنه غير متحقق ويحتاج إلى تأكيد.",
  },
  openReference: { en: "Open reference", ar: "افتح المرجع" },
  openLocalAttachment: { en: "Download local attachment", ar: "نزّل المرفق المحلي" },
  sourcesOpenedFromEvidence: { en: "Sources opened from evidence links", ar: "المصادر المفتوحة من روابط الأدلة" },
  otherSourcesOpened: { en: "Other sources reopened outside Ulomis", ar: "مصادر أخرى أُعيد فتحها خارج أولوميس" },
  sourceCountingHelp: {
    en: "Links and local attachments opened from this view are counted once automatically. Use the counter only for other original sources you reopen elsewhere.",
    ar: "تُحتسب الروابط والمرفقات المحلية المفتوحة من هذا العرض مرة واحدة تلقائيًا. استخدم العداد فقط للمصادر الأصلية الأخرى التي تفتحها في مكان آخر.",
  },
  correctionRecord: { en: "Correction record", ar: "سجل التصحيح" },
  updatedTo: { en: "Updated to", ar: "تم التحديث إلى" },
  correctionRemoveHint: {
    en: "Leave blank to remove this from the current state.",
    ar: "اتركه فارغًا لإزالة هذا من الحالة الحالية.",
  },
  correctionWriteHint: {
    en: "Write only the corrected operational state.",
    ar: "اكتب الحالة التشغيلية المصححة فقط.",
  },
  deleteBoundary: {
    en: "This deletes state and attachments from this browser only. It cannot delete copies you already exported or emailed.",
    ar: "يحذف هذا الحالة والمرفقات من هذا المتصفح فقط. لا يمكنه حذف النسخ التي صدّرتها أو أرسلتها بالبريد بالفعل.",
  },
  linkReferenceBoundary: {
    en: "Links are references only. If the pilot operator cannot access a link, paste the relevant excerpt instead.",
    ar: "الروابط مراجع فقط. إذا تعذّر على مسؤولة التجربة فتح الرابط، الصق المقتطف ذي الصلة بدلًا منه.",
  },
} satisfies Record<string, LocalizedText>;

export const stepLabels: Record<PilotStep, LocalizedText> = {
  1: { en: "Choose the thread", ar: "اختر الخيط" },
  2: { en: "Record baseline", ar: "سجّل خط الأساس" },
  3: { en: "Add the material", ar: "أضف المواد" },
  4: { en: "Confirm the state", ar: "أكّد الحالة" },
  5: { en: "Return and resume", ar: "عُد وتابع" },
  6: { en: "Review the result", ar: "راجع النتيجة" },
};

export const claimLabels: Record<ClaimField, LocalizedText> = {
  objective: { en: "Objective", ar: "الهدف" },
  currentState: { en: "Current state", ar: "الحالة الحالية" },
  latestMeaningfulChange: { en: "Latest meaningful change", ar: "أحدث تغيير جوهري" },
  decision: { en: "Decision", ar: "القرار" },
  rationale: { en: "Why that decision was made", ar: "سبب اتخاذ القرار" },
  commitments: { en: "Commitments", ar: "الالتزامات" },
  dependencies: { en: "Dependencies", ar: "الاعتماديات" },
  unresolvedItems: { en: "Unresolved items", ar: "البنود غير المحسومة" },
  missingInformation: { en: "Missing information", ar: "المعلومات المفقودة" },
  owners: { en: "Owners", ar: "المسؤولون" },
  contradictions: { en: "Contradictions", ar: "التعارضات" },
  nextAction: { en: "Suggested next action", ar: "الخطوة التالية المقترحة" },
};
