/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PilotDavidRouteImport } from './routes/pilot/david'
import { Route as PilotWorkspaceRouteImport } from './routes/pilot/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotDavidRoute = PilotDavidRouteImport.update({
  id: '/pilot/david',
  path: '/pilot/david',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotWorkspaceRoute = PilotWorkspaceRouteImport.update({
  id: '/pilot/workspace',
  path: '/pilot/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pilot/david': typeof PilotDavidRoute
  '/pilot/workspace': typeof PilotWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pilot/david': typeof PilotDavidRoute
  '/pilot/workspace': typeof PilotWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pilot/david': typeof PilotDavidRoute
  '/pilot/workspace': typeof PilotWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pilot/david' | '/pilot/workspace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pilot/david' | '/pilot/workspace'
  id: '__root__' | '/' | '/pilot/david' | '/pilot/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PilotDavidRoute: typeof PilotDavidRoute
  PilotWorkspaceRoute: typeof PilotWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/david': {
      id: '/pilot/david'
      path: '/pilot/david'
      fullPath: '/pilot/david'
      preLoaderRoute: typeof PilotDavidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot/workspace': {
      id: '/pilot/workspace'
      path: '/pilot/workspace'
      fullPath: '/pilot/workspace'
      preLoaderRoute: typeof PilotWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PilotDavidRoute: PilotDavidRoute,
  PilotWorkspaceRoute: PilotWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
